directory: "E:\\Transfer"
days_threshold: 30

schedule:
  enabled: true
  cron: "0 0 * * *"

smtp:
  host: "smtp.office365.com"
  port: 587
  username: "email"
  password: "senha"
  to: "destinatario"